### ISSUE TITLE
Reddit upvote button

### ISSUE THREAD

**Issue by JohannesM** [octatone/reddit.tv#14]
It's not an issue, it's more a feature request. Can we have a reddit upvote / downvote next to the comment link?
So it would be easier, because if I do like a video I have to go trough the link to reddit, upvote, and then returning back.

**Comment by octatone** [comment]
Yeah, the code's already there i just need to enable it.  But before i do that there's some bug in the button code on reddit's end that doesn't resolved some urls correctly.

**Comment by octatone** [comment]
Enabled in latest commits.
