### ISSUE TITLE
Can't view videos in Reddit.tv Boxee app (Boxee software, not box)

### ISSUE THREAD

**Issue by dethkultur** [octatone/reddit.tv#17]
It stopped working about 4-5 days ago... I can see thumbnails, but when I click to watch the video, they all say "This video is currently not available" in a pop up.

In the past, I would get this for maybe 1 out of 20 videos, but now every single video is giving this message. I have tried deleting and redownloading the app from within boxee, even uninstalling boxee, wiping the profile, and reinstalling fresh, but the issue remains. I love this app, and want to use it daily.

**Comment by octatone** [comment]
I've never heard of the reddit.tv boxee app, and it's not managed by me.  This is the source to the reddit.tv website.
