### ISSUE TITLE
Spinner in center of video corrupts image

### ISSUE THREAD

**Issue by starrychloe** [octatone/reddit.tv#18]
The spinner in the center of the video doesn't go away and it corrupts the display of the video. It should be completely hidden after a video loads (or get rid of it altogether). It causes the center of the video to become blocky and lag and every few seconds the spinner image appears on the video. Google Chrome.

**Comment by starrychloe** [comment]
This is the problem, in tv.js, line 200, you add .loading class but you never remove it after it has loaded:

$video_embed.addClass('loading');
https://github.com/octatone/reddit.tv/blob/master/js/tv.js#L200

**Comment by octatone** [comment]
fixed here

https://github.com/octatone/reddit.tv/commit/4c197a370e71e25c6a678cdff2b387fdedf57b99
