### ISSUE TITLE
RedditTV Boxee app missing catagories

### ISSUE THREAD

**Issue by uberg33k** [octatone/reddit.tv#21]
The RedditTV app for Boxee box seems to be completely different from the reddit.tv site.  Several catagories are missing on the Boxee app.  Most notably Docs, Listentothis. Radioreddit, and lectures are absent.  Would it be possible to update the Boxee box app to include these outstanding subreddits.  Thanks.

**Comment by octatone** [comment]
The boxee app has no affiliation with reddit.tv and is not maintained by me.
