### ISSUE TITLE
Categories 

### ISSUE THREAD

**Issue by captainPOC** [octatone/reddit.tv#22]
Can you allow me to watch reddit tv for othe rsubreddits?

I would love to have one for http://www.reddit.com/r/reggae/ for example.

Why don't you allow the user to select/type in any subreddit they want?

**Comment by octatone** [comment]
This is in the pipeline, but currently I'm working on adding more functionality for intereaction with the different video embeds.

**Comment by captainPOC** [comment]
NICE 1
 
do let me know

 

On 22 September 2011 at 19:04 "Raymond May Jr."
reply@reply.github.com
wrote:

**Comment by octatone** [comment]
Check it: http://reddit.tv/#/r/reggae

**Comment by captainPOC** [comment]
Raymond,
 
much love and respect for this adjustment to your application.
 
i will post the link on /r/reggae. you should incur many hits.
 
May happiness rain on your soul! jah bless
 
 

 

On 20 October 2011 at 20:02 "Raymond May Jr."
reply@reply.github.com
wrote:

**Comment by captainPOC** [comment]
wow, i can do any subreddit!  you are officially a badman!

 

On 20 October 2011 at 20:02 "Raymond May Jr."
reply@reply.github.com
wrote:
