### ISSUE TITLE
...it would be nice(tm) if soundcloud links were also supported

### ISSUE THREAD

**Issue by ramses0** [octatone/reddit.tv#25]
http://reddit.tv/#/r/classicalguitar/ ... we've got quite a few people who post links to soundcloud of themselves playing instead of videos.  I don't know if that necessarily matches the core competency of reddit.tv but it seems like it would make sense for our specific use case.  Just don't know if you'd considered it before or not.

Thanks!

**Comment by octatone** [comment]
Reddit.tv is specifically for watching videos.
