### ISSUE TITLE
Remove vice?

### ISSUE THREAD

**Issue by ghost** [octatone/reddit.tv#37]
I've been using your source for a while but I just updated, and it's using the vice theme and has all the advertising and whatnot. 

Can you release it without this or leave instructions on how to turn it off?

The main site doesn't even seem to use that anymore.

**Comment by tbow2000** [comment]
I need to learn how to code.

**Comment by twohlix** [comment]
Just undo the filling of the Promo object in tv.js or delete it. Look at this commit for how he added it: 7165eaba1b01b613fa0b2b66842d8bfa880fff65 

All you have to do is remove lines 32 - 57 from tv.js. see: [js.tv](/octatone/reddit.tv/blob/8addd0d3aa008de9f16960e43a4435d4115ca7a7/js/tv.js#L32-L57)
