### ISSUE TITLE
Sometimes "Next" button won't work after viewing a few videos

### ISSUE THREAD

**Issue by RedditTVviewer** [octatone/reddit.tv#6]
Even after refreshing the page, it won't progress to the next video. I have to select another category before it will work. Even waiting for the end of the video does not trigger the autoplay/advance

**Comment by octatone** [comment]
You'll have to provide more information for us to track down the bug.  Be aware that sometimes there are only a few fresh videos per feed.

What browser are you using, what operating system, what channel were you watching, what video were you watching.  Can you open up a debugger a trace the failure?

**Comment by octatone** [comment]
Actually, it's not mentioned on the site, but auto advance and fill screen only work with youtube videos right now.  So maybe that is what you are running into.

**Comment by fagga** [comment]
Maybe this is because the end of the playlist is reached?

That’s another issue anyway. The NEXT and PREV buttons should be disabled visually if they don’t do anything. I’ll look into this.
